addons:
  apt:
    packages:
      - xvfb
before_install:
  - npm install -g npm@3
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
os:
  - linux
  - osx
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_script:
  - npm prune
after_success:
  - npm run semantic-release
